#create a set of numbers on input

s=set()
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
print(s)